### ISSUE TITLE
Bad headers. Expected "X-CSRF-Token" in headers

### ISSUE THREAD

**Issue by sonn-gamm** [aekasitt/fastapi-csrf-protect#16]
Hi!

Thanks a lot for this library. I came back to it after using it around 6 months ago, and things have recently changed. 

I encountered an error, which is happening also when testing the example app provided in the repo. Which is:

upon sending the login form, I get back a `Bad headers. Expected "X-CSRF-Token" in headers`. Browsing around the codebase, I found this error has a test (https://github.com/aekasitt/fastapi-csrf-protect/blob/master/tests/missing_token.py#L54-L57), and when running `pytest` all tests pass!

In your code example you pass a [`csrf_token` to the template](https://github.com/aekasitt/fastapi-csrf-protect/blob/master/examples/login.py#L40), but in the HTML template you never use it. As far as I understand, the Double Submit Cookie technique employs both a cookie CSRF token as well as sending the same token through a form data.

I tried to add a hidden input to the form with the CSRF token, but clearly it does not help, as indeed the raised error is about a missing header, not about form data.

Any idea why this is happening? Are we expected to submit the form via javascript, in which case we can manually add an X-CSRF-Token to the HTTP call ourselves?

If so, it would be useful to extend the README and including this last bit of info.

Moreover, if this is the case, then I don't think this is an implementation of the Double Submit Cookie, as the second CSRF token should be instead submitted via a form data.

Thanks!

**Comment by aekasitt** [comment]
Will look into this immediately and rewrite example to match. I think the Double Submit Cookies pattern presented a breaking change from version 0.2 to 0.3

**Comment by aekasitt** [comment]
Code example now uses JavaScript which can make use of Jinja2 embedded context var, for post request instead of `<form></form>` tag submission. Hope this helps!

**Comment by matslindh** [comment]
This change in 0.3.0 broke usage of the library for creating and validating regular http form csrf tokens. It's now impossible to validate a CSRF token without it being included in a token and in a header - just having the expected CSRF token as a form field in a regular form is not longer possible, as the implementation is closely tied to using a cookie and a header, the latter which can't be set in a form context.

**Comment by aekasitt** [comment]
Completely agreed on the form > JavaScript integration.
---
However, after having concerns raised about "CSRF token validation is incomplete (does not validate uniqueness per browser session" #11 , the previous behavior needed immediate amending and I decided to mimic the example of [tiny-csrf](https://github.com/valexandersaulys/tiny-csrf) on JavaScript

---
```
> In your code example you pass a csrf_token, but in the HTML template you never use it.
> As far as I understand, the Double Submit Cookie technique employs both a cookie CSRF token
> as well as sending the same token through a form data.
```

This can still be achieved by adding the following input-tag in the form interpreted by Jinja2 templating...
```html
<input type='hidden' name='csrf-token' value="{{ csrf_token }}"/>
```

But the library is lacking capability to parse through request body as of yet. I will try my best to add this feature in `0.3.2` and break the example usage into two, one using form submission and one using ajax headers. Your finding out the hard way is still my responsibility and I want to own up to it.  I hope I can put the library up to a state where changes don't break your implementation.

**Comment by matslindh** [comment]
First: no worries; libraries with a 0.x tag aren't assumed to be in any stable condition :-)

Yes, the problem is that the `validate_csrf`-function has been closely tied to cookie + header now, instead of letting us supply the csrf token itself as previously - so we're not able to move back to the old solution (just including the token is fine, but we can't validate it). 

In those cases where we're concerned with re-use of these tokens (which in effect hasn't really been an issue), we've included a timestamp in the signed value - so that the token itself is self-contained with both an expiry value and the token that is valid until that expiry. That way you get short-ish-lived tokens, but don't have to introduce additional cookies (which require documentation in privacy policies, etc.) or similar things.

**Comment by aekasitt** [comment]
Had some work done on this in the last few commits. Would you mind giving comments on it? If satisfactory, will publish to `0.3.2` now.

**Comment by Androsakrist** [comment]
hi, i just had a similar problem regarding this issue. 

so i tried to use the token-key location in the headers. i thought it might put the output or response of /csrftoken, which is the token key into the headers automatically. Btw, im using postman to test my API. The  /csrftoken api works good, and give the expected response. 
The problem comes up when i try to use the token on another API that required to validate the X-CSRF-Token. The exception massage was exactly the same as in the title of this issue. I managed to solve by manually tipe the defined token key  in the request header with the value that i got from the /csrftoken API. 

IDK if i supposed to input the token value manually in headers or the set_csrf_cookie should automatically do it. But if i may suggest it might be great if the function could do that in the future. 

I put the API down below if theres any comment on issue i had. Thank You. 
```python
@app.get("/csrftoken")
async def get_csrf_token(request: Request, csrf_protect:CsrfProtect = Depends()):
    csrf_token, signed = csrf_protect.generate_csrf_tokens()
    response = JSONResponse(status_code=200, content= {"csrf_token": csrf_token})
    csrf_protect.set_csrf_cookie(csrf_signed_token=signed, response=response)
    return response

```
