### ISSUE TITLE
.get_csrf_from_body() fails with Input should be a valid dictionary or instance of Body

### ISSUE THREAD

**Issue by yyyyyyyan** [aekasitt/fastapi-csrf-protect#26]
The current implementation of `.get_csrf_from_body()` doesn't seem to work, at least not with latest Pydantic, as it does not (automatically) coerce a string into a dict. If the form wasn't read before the call to `csrf_protect.validate_csrf(request)`, `request._form` is None and `.get_csrf_from_body()` fails with `Input should be a valid dictionary or instance of Body`.

https://github.com/aekasitt/fastapi-csrf-protect/pull/20 should fix it, but it wasn't merged for some reason.

**Comment by aekasitt** [comment]
fixed in version `0.3.7`
fix: library used deprecated methods by pydantic, changed that to modern alternatives
reason why PR#20 was not merged and merged PR#21 instead was written in those PRs
tl;dr: pydantic does as good of a job at parsing body data with a few tweaks, saw no reason to expand dependencies

**Comment by aekasitt** [comment]
Thank you for raising the issue.

**Comment by aekasitt** [comment]
Regarding rejecting #20 and accepting #21 
We avoided [CVE-2024-53981](https://github.com/advisories/GHSA-59g5-xgcq-4qw3/dependabot) for not adding python-multipart to our dependencies.
